language: node_js
node_js:
- 6.7.0
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install -g typescript hexo-cli
- npm install
- tsc -p ./client
- tsc -p ./server
- npm run bundle:prod
- cd docs/pre-source
- curl -L https://github.com/nativescript/docs/archive/v2.0.1.tar.gz | tar zx
- curl -L https://github.com/nativescript/docs/archive/v2.2.0.tar.gz | tar zx
- curl -L https://github.com/nativescript/docs/archive/production.tar.gz | tar zx
- cd ..
- npm install
- node build.js
- hexo generate
deploy:
  provider: heroku
  app: ns-docs
  skip_cleanup: true
  on:
    repo: georgeedwards/docs
    branch: production
  api_key:
    secure: n7nb+OrrHKUvtEdru40T80u+vwtv/xd9mLD9oAokng51sgbsfchfUcRcm5J/o+hEDjwZzuDPvXd9IsqVhOAmB1KWFNDAydr58U6Z+tM3yXuoqE/FrzeThzOaeEE7DGvOsONoAmuAXdm/hnoyvf0+6+b1kqi9E/iL8RyWGHe/jpMncVHHuZwT07bmBi2s+2jb8C/fv/G27zVgt3hkvZUBDOxBHHn65D7zyclbeoXLJvUWeGJEViUhig3XLF6oahBUEYt7ivDLyqdSghH6azzCKHD294i42DMzL9csAujIpXqTOEShLFCs8teSx5kwgJqrC2VKahiS4T2oX8W/gWesVacnv59TJ5jz8CMkC7RCow8/IX+TXDxI2Dmw0D121/AHx9XEw6fzjURbrUDvLWEM7WeZVq77MzLtWiA3SeVpx3GFL1LLLbVMsb2XvcyBKYw00tkeKPxn2hudWl9GEiEv5aH2Ue16CTZEFSLuLDU9ldGuyFYHVwX4CnTbLnVcLBb86b1cTVoIDAzSIi2GmbLBFcbBabmvMlrEXXDAvVeD0Xb0nWcw1MVTQigQZyVf96kvZUCjg8OO/l2++tFXMQAR2lgHs1HRkKVdkixwTtv0o1/nibauU1vu+avjSCxLiaq/sUp7DWnw5pR+bUXGNZZxKWdXBxCu5Sa7Hlk+rFGuqVY=
