# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Nativescript Docs
subtitle: API Docs
description:
author:
language:
timezone:
apis:
  marketo: 627-RVJ-941
  segment: zQx6cQifkTU79E3L0XAnmrOXP2A5bC6r
  docsearch:
    apiKey: bdf6b09d12024f6bae3631a0dfdd4a7f
    indexName: meteor_api_guide
versions:
  - '1.3.4'
  - '1.3.3'
  - '1.3.2'
sidebar_categories:
  null:
    - index
  UI:
    - ui/animation-css
    - ui/action-bar
    - ui/animation-code
    - ui/animation-examples
    - ui/animation
    - ui/keyboard
    - ui/icon-fonts
    - ui/gestures
    - ui/change-status-bar-style-ios
    - ui/layout-containers
    - ui/ui-dialogs
    - ui/layouts
    - ui/list-view
    - ui/placeholder
    - ui/ui-images
    - ui/styling
    - ui/ui-with-xml
    - ui/ui-views
  Cookbook:
    - cookbook/formatted-string-ng
    - cookbook/tab-view-ng
  Hardware:
    - hardware/camera
    - hardware/location
  Plugins:
    - plugins/plugins
    - plugins/angular-third-party
    - plugins/cocoapods
    - plugins/ui-plugin

github_repo: 'meteor/docs'
content_root: 'source'

# themeing
favicon: '../images/favicon.png'

front_end: nativescript
logo:
  nav_mobile: '../images/logo-blue.svg'
  sidebar: '../images/icon-white.svg'
  url: 'http://www.meteor.com/developers'
  title: 'Nativescript Developers'
  target: _new

nav_links:
  'Tutorials':
    url: http://www.meteor.com/tutorials
    partial: illustration-guide
    target: _new
  'Guide':
    url: http://guide.meteor.com
    partial: illustration-compass
  'API Docs':
    url: http://docs.meteor.com
    partial: illustration-logs
    active: true
  'Forums':
    url: https://forums.meteor.com/
    partial: illustration-support
    target: _new

social_links:
  github: 'https://github.com/meteor'
  twitter: '@meteor'


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://docs.meteor.com/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: nativescript
api_box:
  data_file: 'data/data.js'
marked:
  breaks: false
  gfm: true

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:

# Redirects. This was generated by conversion/convert-toc-redirects.js
# NOTE that scripts/old-redirects runs FIRST before this more static mapping
redirects:
